### ISSUE TITLE
[BUG] Getting error when Protocol is typed with large starting letter

### ISSUE THREAD

**Issue by tomasnorre** [michiel-roos/xposer-issues#1]
I experience this bug as I was trying it out on my Mobile, the autocorrection started the Https with a large starting letter, and that's when i saw the problem.

*Actual behaviour* 
1. go to xposer.io
2. type `Https://www.typo3.com` The large start letter is important.
3. You will get the error: `https://Https DNS error. Unable to resolve host`

*Expected behaviour* 
1. go to xposer.io
2. type `Https://www.typo3.com` The large begin letter is important.
3. You will get the version as result.

**Comment by Tuurlijk** [comment]
Hi Tomas,

Thank you for your report. Should be fixed as of now.

**Comment by tomasnorre** [comment]
Is working, thanks.
