### ISSUE TITLE
AMO: use https instead of http

### ISSUE THREAD

**Issue by grahamperrin** [michiel-roos/xposer-issues#2]
Nit: the description uses http:// for the links to `xposer.io`

![image](https://user-images.githubusercontent.com/192271/70387138-2cc4b100-1999-11ea-879b-7c99efb1e25f.png)

**Comment by Tuurlijk** [comment]
Hi,

Thank you for the report. The description just had 'xposer.io' The http:// was added by AMO. I have now updated the summary and description to use https://
